Update backend-validator.yml

diff --git a/.github/workflows/backend-validator.yml b/.github/workflows/backend-validator.yml
--- a/.github/workflows/backend-validator.yml
+++ b/.github/workflows/backend-validator.yml
@@ -61,7 +61,8 @@ jobs:
        go build openeoct.go
        ./openeoct config /home/runner/work/TestRepo/TestRepo/config.json
        content=`cat ./validator_output.json`
-       echo "::result=packageJson::$content" 
+       echo "::result=packageJson::$content" | grep -v "Error"
+       echo $?
        
     - name: Docker Stop   
       run: |
