Update backend-validator.yml

diff --git a/.github/workflows/backend-validator.yml b/.github/workflows/backend-validator.yml
--- a/.github/workflows/backend-validator.yml
+++ b/.github/workflows/backend-validator.yml
@@ -57,6 +57,9 @@ jobs:
        go get github.com/mcuadros/go-version
        go build openeoct.go
        ./openeoct config /home/runner/work/TestRepo/TestRepo/config.json
+       echo '"endpoints": {"group_summary": "Invalid"}' | grep -v Error
+       if: ($? = 1)  
+       exit 1
        
     - name: Docker Stop   
       run: |
