Update backend-validator.yml

diff --git a/.github/workflows/backend-validator.yml b/.github/workflows/backend-validator.yml
--- a/.github/workflows/backend-validator.yml
+++ b/.github/workflows/backend-validator.yml
@@ -59,9 +59,8 @@ jobs:
        go get github.com/BurntSushi/toml
        go get github.com/mcuadros/go-version
        go build openeoct.go
-       echo './openeoct config /home/runner/work/TestRepo/TestRepo/config.json' | grep -v "home"
-       echo $?
-
+       echo './openeoct config /home/runner/work/TestRepo/TestRepo/config.json' | grep -v "Error"
+       echo $? 
        
     - name: Docker Stop   
       run: |
