Update backend-validator.yml

diff --git a/.github/workflows/backend-validator.yml b/.github/workflows/backend-validator.yml
--- a/.github/workflows/backend-validator.yml
+++ b/.github/workflows/backend-validator.yml
@@ -56,10 +56,11 @@ jobs:
        go get github.com/BurntSushi/toml
        go get github.com/mcuadros/go-version
        go build openeoct.go
-       ./openeoct config /home/runner/work/TestRepo/TestRepo/config.json
-       echo '"endpoints": {"group_summary": "Invalid"}' | grep -v Error
-       if: (echo $? = 1)  
+       ./openeoct config /home/runner/work/TestRepo/TestRepo/config.json | grep -v "Invalid"
+       echo $? 
        exit 1
+       
+       #echo '"endpoints": {"group_summary": "Invalid"}'
        
     - name: Docker Stop   
       run: |
